global using MediatR;
global using Microsoft.AspNetCore.Http;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using System.Data;
global using Trasen.PaperFree.Domain.ArchiveRecord.Entity;
global using Trasen.PaperFree.Domain.SeedWork;
global using Trasen.PaperFree.Domain.Shared.Const;